import { NgModule } from '@angular/core';
import { PreloadAllModules, RouterModule, Routes } from '@angular/router';

const routes: Routes = [
  { path: '', loadChildren: './pages/home/home.module#HomePageModule' },
  { path: 'tabs', loadChildren: './tabs/tabs.module#TabsPageModule' },
  { path: 'login', loadChildren: './pages/login/login.module#LoginPageModule' },
  { path: 'changepassword', loadChildren: './modalpage/changepassword/changepassword.module#ChangepasswordPageModule' },
  { path: 'changepassword/:value', loadChildren: './modalpage/changepassword/changepassword.module#ChangepasswordPageModule' },
  { path: 'edit-profile-info', loadChildren: './pages/edit-profile-info/edit-profile-info.module#EditProfileInfoPageModule' },
  { path: 'edit-profile-info/:firstlogin', loadChildren: './pages/edit-profile-info/edit-profile-info.module#EditProfileInfoPageModule' },
  { path: 'edit-profile-business-card', loadChildren: './pages/edit-profile-business-card/edit-profile-business-card.module#EditProfileBusinessCardPageModule' },
  { path: 'edit-profile-preferences', loadChildren: './pages/edit-profile-preferences/edit-profile-preferences.module#EditProfilePreferencesPageModule' },
  { path: 'edit-profile-company', loadChildren: './pages/edit-profile-company/edit-profile-company.module#EditProfileCompanyPageModule' },
  { path: 'social-media', loadChildren: './modalpage/social-media/social-media.module#SocialMediaPageModule' },
  { path: 'settings', loadChildren: './pages/settings/settings.module#SettingsPageModule' },
  { path: 'cms/:key', loadChildren: './pages/cms/cms.module#CmsPageModule' },
  { path: 'delegate-profile', loadChildren: './pages/delegate-profile/delegate-profile.module#DelegateProfilePageModule' },
  { path: 'tabs/event/:event_id', loadChildren: './pages/event/event.module#EventPageModule' },
  //{ path: 'tabs/event/:event_id', loadChildren: () => import('./pages/delegate-profile/delegate-profile.module').then( m => m.DelegateProfilePageModule) },   
  { path: 'delegate-profile/:delegate_id/:event_id', loadChildren: './pages/delegate-profile/delegate-profile.module#DelegateProfilePageModule' },
  { path: 'event-filter', loadChildren: './modalpage/event-filter/event-filter.module#EventFilterPageModule' },
  { path: 'prompt-modal', loadChildren: './modalpage/prompt-modal/prompt-modal.module#PromptModalPageModule' },
  { path: 'edit-user-profile', loadChildren: './pages/edit-user-profile/edit-user-profile.module#EditUserProfilePageModule' },
  { path: 'filter-delegate', loadChildren: './modalpage/filter-delegate/filter-delegate.module#FilterDelegatePageModule' },
  { path: 'tabs', loadChildren: './tabs/tabs.module#TabsPageModule' },
  { path: 'chat', loadChildren: './pages/chat/chat.module#ChatPageModule' },
  { path: 'notification', loadChildren: './pages/notification/notification.module#NotificationPageModule' },
  { path: 'event-settings', loadChildren: './pages/event-settings/event-settings.module#EventSettingsPageModule' },
  { path: 'sponsor-profile', loadChildren: './pages/sponsor-profile/sponsor-profile.module#SponsorProfilePageModule' },
  { path: 'event-profile/:event_id', loadChildren: './pages/event-profile/event-profile.module#EventProfilePageModule' },
  { path: 'event-location', loadChildren: './pages/event-location/event-location.module#EventLocationPageModule' },
  { path: 'event-floorplan', loadChildren: './pages/event-floorplan/event-floorplan.module#EventFloorplanPageModule' },
  { path: 'speaker-profile', loadChildren: './pages/speaker-profile/speaker-profile.module#SpeakerProfilePageModule' },
  { path: 'schedule-meeting', loadChildren: './modalpage/schedule-meeting/schedule-meeting.module#ScheduleMeetingPageModule' },
  { path: 'schedule-meeting-info', loadChildren: './modalpage/schedule-meeting-info/schedule-meeting-info.module#ScheduleMeetingInfoPageModule' },
  { path: 'meeting-details', loadChildren: './pages/meeting-details/meeting-details.module#MeetingDetailsPageModule' },
  { path: 'prompt-modal-header', loadChildren: './modalpage/prompt-modal-header/prompt-modal-header.module#PromptModalHeaderPageModule' },
  { path: 're-schedule-meeting', loadChildren: './modalpage/re-schedule-meeting/re-schedule-meeting.module#ReScheduleMeetingPageModule' },
  { path: 'add-notes', loadChildren: './pages/add-notes/add-notes.module#AddNotesPageModule' },
  { path: 'add-notes/:event_delegate_id/:meeting_schedule_id', loadChildren: './pages/add-notes/add-notes.module#AddNotesPageModule' },
  { path: 'event-meeting-request/:event_id', loadChildren: './pages/event-meeting-request/event-meeting-request.module#EventMeetingRequestPageModule' },
  { path: 'delegate-locator/:event_id', loadChildren: './pages/delegate-locator/delegate-locator.module#DelegateLocatorPageModule' },
  { path: 'noshow-delegates/:event_id', loadChildren: './pages/noshow-delegates/noshow-delegates.module#NoshowDelegatesPageModule' },
  { path: 'event-meeting-request-list', loadChildren: './modalpage/event-meeting-request-list/event-meeting-request-list.module#EventMeetingRequestListPageModule' },
  { path: 'cancel-meeting-request', loadChildren: './modalpage/cancel-meeting-request/cancel-meeting-request.module#CancelMeetingRequestPageModule' },
  { path: 'event-notes/:event_id', loadChildren: './pages/event-notes/event-notes.module#EventNotesPageModule' },
  { path: 'note/:event_id/:note_id', loadChildren: './pages/note/note.module#NotePageModule' },
  { path: 'note-send-mail', loadChildren: './modalpage/note-send-mail/note-send-mail.module#NoteSendMailPageModule' },
  { path: 'forgot-password', loadChildren: './pages/forgot-password/forgot-password.module#ForgotPasswordPageModule' },
  { path: 'chatbox', loadChildren: './modalpage/chatbox/chatbox.module#ChatboxPageModule' },
  { path: 'event-feedback/:event_id', loadChildren: './pages/event-feedback/event-feedback.module#EventFeedbackPageModule' },
  { path: 'event-faq/:event_id', loadChildren: './pages/event-faq/event-faq.module#EventFaqPageModule' },
  { path: 'event-faq-profile/:event_id/:faq_id', loadChildren: './pages/event-faq-profile/event-faq-profile.module#EventFaqProfilePageModule' },
  { path: 'custom-selectable', loadChildren: './modalpage/custom-selectable/custom-selectable.module#CustomSelectablePageModule' },
  { path: 'custom-selectable-state', loadChildren: './modalpage/custom-selectable-state/custom-selectable-state.module#CustomSelectableStatePageModule' },
  { path: 'image-cropper', loadChildren: './modalpage/image-cropper/image-cropper.module#ImageCropperPageModule' },
  { path: 'enhance-tabs', loadChildren: './enhance-tabs/enhance-tabs.module#EnhanceTabsPageModule' },
  { path: 'event-enhance/:event_id', loadChildren: './enhancements/event-enhance/event-enhance.module#EventEnhancePageModule' },
  { path: 'chat-enhance', loadChildren: './enhancements/chat-enhance/chat-enhance.module#ChatEnhancePageModule' },
  { path: 'notification-enhance', loadChildren: './enhancements/notification-enhance/notification-enhance.module#NotificationEnhancePageModule' },
  { path: 'event-settings-enhance/:event_id', loadChildren: './enhancements/event-settings-enhance/event-settings-enhance.module#EventSettingsEnhancePageModule' },
  { path: 'meeting-details-enhance', loadChildren: './enhancements/meeting-details-enhance/meeting-details-enhance.module#MeetingDetailsEnhancePageModule' },
  { path: 'enhance-tabs', loadChildren: './enhance-tabs/enhance-tabs.module#EnhanceTabsPageModule' },
  { path: 'event-profile-enhance/:event_id', loadChildren: './enhancements/event-profile-enhance/event-profile-enhance.module#EventProfileEnhancePageModule' },
  { path: 'speaker-profile-enhance', loadChildren: './enhancements/speaker-profile-enhance/speaker-profile-enhance.module#SpeakerProfileEnhancePageModule' },
  { path: 'sponsor-profile-enhance', loadChildren: './enhancements/sponsor-profile-enhance/sponsor-profile-enhance.module#SponsorProfileEnhancePageModule' },
  { path: 'schedule-meeting-enhance', loadChildren: './enhance-modalpage/schedule-meeting-enhance/schedule-meeting-enhance.module#ScheduleMeetingEnhancePageModule' },
  { path: 'schedule-meeting-info-enhance', loadChildren: './enhance-modalpage/schedule-meeting-info-enhance/schedule-meeting-info-enhance.module#ScheduleMeetingInfoEnhancePageModule' },
  { path: 'prompt-modal-enhance', loadChildren: './enhance-modalpage/prompt-modal-enhance/prompt-modal-enhance.module#PromptModalEnhancePageModule' },
  { path: 'prompt-modal-header-enhance', loadChildren: './enhance-modalpage/prompt-modal-header-enhance/prompt-modal-header-enhance.module#PromptModalHeaderEnhancePageModule' },
  { path: 're-schedule-meeting-enhance', loadChildren: './enhance-modalpage/re-schedule-meeting-enhance/re-schedule-meeting-enhance.module#ReScheduleMeetingEnhancePageModule' },
  { path: 'cancel-meeting-request-enhance', loadChildren: './enhance-modalpage/cancel-meeting-request-enhance/cancel-meeting-request-enhance.module#CancelMeetingRequestEnhancePageModule' },
  { path: 'note-send-mail-enhance', loadChildren: './enhance-modalpage/note-send-mail-enhance/note-send-mail-enhance.module#NoteSendMailEnhancePageModule' },
  { path: 'chatbox-enhance', loadChildren: './enhance-modalpage/chatbox-enhance/chatbox-enhance.module#ChatboxEnhancePageModule' },
  { path: 'filter-delegate-enhance', loadChildren: './enhance-modalpage/filter-delegate-enhance/filter-delegate-enhance.module#FilterDelegateEnhancePageModule' },
  { path: 'edit-profile-info-enhance', loadChildren: './enhancements/edit-profile-info-enhance/edit-profile-info-enhance.module#EditProfileInfoEnhancePageModule' },
  //{ path: 'edit-user-profile-enhance', loadChildren: './enhancements/edit-user-profile-enhance/edit-user-profile-enhance.module#EditUserProfileEnhancePageModule' },
  { path: 'event-meeting-request-enhance/:event_id', loadChildren: './enhancements/event-meeting-request-enhance/event-meeting-request-enhance.module#EventMeetingRequestEnhancePageModule' },
  { path: 'event-meeting-request-list-enhance', loadChildren: './enhance-modalpage/event-meeting-request-list-enhance/event-meeting-request-list-enhance.module#EventMeetingRequestListEnhancePageModule' },
  { path: 'setting-enhance', loadChildren: './enhancements/setting-enhance/setting-enhance.module#SettingEnhancePageModule' },
  { path: 'event-notes-enhance/:event_id', loadChildren: './enhancements/event-notes-enhance/event-notes-enhance.module#EventNotesEnhancePageModule' },
  { path: 'add-notes-enhance', loadChildren: './enhancements/add-notes-enhance/add-notes-enhance.module#AddNotesEnhancePageModule' },
  { path: 'add-notes-enhance/:event_delegate_id/:meeting_schedule_id', loadChildren: './enhancements/add-notes-enhance/add-notes-enhance.module#AddNotesEnhancePageModule' },
  { path: 'note-enhance', loadChildren: './enhancements/note-enhance/note-enhance.module#NoteEnhancePageModule' },
  { path: 'note-enhance/:event_id/:note_id', loadChildren: './enhancements/note-enhance/note-enhance.module#NoteEnhancePageModule' },
  { path: 'event-itinerary', loadChildren: './enhancements/event-itinerary/event-itinerary.module#EventItineraryPageModule' },
  { path: 'file-option', loadChildren: './modalpage/file-option/file-option.module#FileOptionPageModule' },
];

@NgModule({
  imports: [
    RouterModule.forRoot(routes, { preloadingStrategy: PreloadAllModules })
  ],
  exports: [RouterModule]
})
export class AppRoutingModule {}
