export const Urls = {
    api_cms_get: '/api/cms/page',
    api_company_get: '/api/company/get',
    api_company_save: '/api/company/save',
    api_delegates_get: '/api/delegates/get',
    api_delegates_save: '/api/delegates/save',
    api_eventdelegate_get: '/api/eventdelegate/get',
    api_events_get: '/api/events/get',
    api_meetingschedule_availablebytimeslot: '/api/meetingschedule/availablebytimeslot',
    api_meetingschedule_set: '/api/meetingschedule/set',
    api_preferences_get: '/api/preferences/get',
    api_sponsor_get: '/api/sponsor/get',
    api_speaker_get: '/api/speaker/get',
    get_token: '/api/token/get',
    mapi_delegate_changepass: '/mapi/delegate/changepass',
    mapi_delegate_checkpass: '/mapi/delegate/checkpassword',
    mapi_delegate_changepushnotif: '/mapi/delegate/changepushnotif',
    mapi_delegate_meetingschedule: '/mapi/delegate/meetingschedule',
    mapi_delegate_meetingrequest: '/mapi/delegate/meetingrequest',
    mapi_delegate_meetingrequestaction: '/mapi/delegate/meetingrequestaction',
    mapi_delegate_meetingrequestlist: '/mapi/delegate/meetingrequestlist',
    mapi_delegate_requestcancelmeeting: '/mapi/delegate/requestcancelmeeting',
    mapi_delegate_availabletimeslot: '/mapi/delegate/availabletimeslot',
    mapi_event_delegates: '/mapi/event/delegates',
    mapi_event_note: '/mapi/event/note',
    mapi_event_schedule: '/mapi/event/schedule',
    mapi_event_scheduleddelegate: '/mapi/event/scheduleddelegate',
    mapi_login_index: '/mapi/login',
    mapi_timeslot_status: '/mapi/timeslot/status',
    mapi_notes_delete: '/mapi/notes/delete',
    mapi_notes_get: '/mapi/notes/get',
    mapi_notes_save: '/mapi/notes/save',
    mapi_notes_sendtoemail: '/mapi/notes/sendtoemail',
    mapi_noshow_topnoshow: '/mapi/noshow/topnoshow',
    mapi_noshow_report: '/mapi/noshow/report',
    mapi_noshow_cancel: '/mapi/noshow/cancel',
    mapi_delegate_locator : '/mapi/delegate/locator',
    mapi_language_get: '/mapi/language/get',
    mapi_delegate_forgotpass : '/mapi/delegate/forgotpassword',
    api_notification_get: '/api/notification/get',
    api_notification_changestatus: '/api/notification/changestatus',
    api_notification_getunreadcount: '/api/notification/getunreadcount',
    api_feedback_save: '/api/feedback/save',
    api_faq_category_get: '/api/faqs/getcategory',
    api_faqs_get: '/api/faqs/get',
    api_faqs_savefaqvote: '/api/faqs/savefaqvote',
    mapi_sessionstats_save: '/mapi/sessionstats/save',
    api_featurecomparison_save: '/api/featurecomparison/save',
    mapi_logout: '/mapi/login/logout',
    mapi_platform_save: '/mapi/platform/save',
    mapi_meetingsched_samecompany: '/mapi/meetingsched/samecompany',
    api_chat_setasread: '/api/chat/setasread',
    api_virtualmeeting_set: '/api/meetingschedule/setvirtual',

    //enhancements
    mapi_event_schedulevirtual: '/mapi/event/schedulevirtual',
    api_delegate_meetingitinerary: '/mapi/delegate/meetingitinerary',
    api_delegates_senditineraries: '/api/delegates/senditineraries',
    api_delegates_sendmultipleitineraries: '/api/delegates/sendmultipleitineraries',
    api_delegates_settimezone: '/api/delegates/settimezone',
    api_events_gettimezone : '/api/events/gettimezone',
    api_events_getvirtual: '/api/events/getvirtual',
    api_virtualconference_shortenurl : '/mapi/virtualconference/shortenurl',
    api_virtualconference_getzoomsettings : '/mapi/virtualconference/getzoomsettings',
}

